### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by basdp** [mcheung63/GKD#3]
I have troubles downloading the dependencies. Can you update the compile section? For instance, on the sourceforge sites I can only find .jar files, which I can't run `mvn clean install` on... (forgive my  lack of JAVA knowledge...)

Thanks!

**Comment by mcheung63** [comment]
Hi Basdp
    please read http://peter.kingofcoders.com/?page_id=1646 , don't download the jar, checkout the source code and run "mvn clean install" in the root folder of every projects, remember to run it in order because they rely on each order but in sequence.
