### ISSUE TITLE
Qemu无法正常使用

### ISSUE THREAD

**Issue by jinghang** [mcheung63/GKD#4]
你好，我无法使用Qemu作为模拟来调试，我的
gkd_qemu.xml 如下：
![image](https://cloud.githubusercontent.com/assets/3844686/20475795/673a9eba-b008-11e6-9fbb-ba0c0bcdad94.png)

通过如下命令运行：
`java -jar GKD-20160622.jar -f gkd_qemu.xml -debug`
抛出异常：
![image](https://cloud.githubusercontent.com/assets/3844686/20475871/e830735a-b008-11e6-9c2e-bf906f643db7.png)

GKD能正常显示界面，但里边无数据，如下：
![image](https://cloud.githubusercontent.com/assets/3844686/20476078/1704b5d2-b00a-11e6-910e-d64a17086004.png)

开发环境：
ubuntu 15.10 32位
Qemu 版本 ：
`QEMU emulator version 2.3.0 (Debian 1:2.3+dfsg-5ubuntu9.4), Copyright (c) 2003-2008 Fabrice Bellard`

如果用命令
`qemu-system-x86_64 -fda c.img`
可以正常运行Qemu。
如果用 Bochs作为模拟器，可以正常调式。

麻烦你帮忙看下，谢谢！

**Comment by mcheung63** [comment]
QQ 348478154, add me and discuss please. you are an university student?

Peter.


________________________________

**Comment by jinghang** [comment]
OK ,thank you very much.no,I'm not a student.
